default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: Abby2020#

development:
  <<: *default
  database: hello_react_development

test:
  <<: *default
  database: hello_react_test

production:
  <<: *default
  database: FriendList_production
  username: FriendList
  password: <%= ENV["FRIENDLIST_DATABASE_PASSWORD"] %>
